name: Selenium/UITestSelenium_(32)
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Run a one-line script
      run: echo Hello, world!
    - run: |-
        # Write your commands here
        echo 'Hello world'
      shell: bash
    - name: Run a multi-line script
      run: |-
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
